<a href="https://colab.research.google.com/github/Nkharshith/numpy_by_me/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Numpy**

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


**2. Creating Arrays
Learn:
1D arrays
2D arrays
3D arrays**

In [ ]:
#1D Array
A = np.array([1,2,3,4,5,6])
print(A)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
#2D Array
B = np.array([[1,2,3],[4,5,6]])
print(B)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3D array
C = np.array([[[2,3],[4,5],[6,7]]])
print(C)

[[[2 3]
  [4 5]
  [6 7]]]


##### **Attributes Numpy array**

In [ ]:
print(A.ndim)

print(B.ndim)

print(C.ndim)

1
2
3


In [ ]:
#Size=rows×columns
A.size

6

In [ ]:
A.shape

(6,)

In [ ]:
A.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#because 6 elements × 8 bytes = 48 bytes
A.nbytes

48

In [ ]:
#Shows datatype of elements.
A.dtype

dtype('int64')

In [ ]:
#Shows memory used by one element (in bytes).
print(A.itemsize)

8


In [ ]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
print("Dimensions:", a.ndim)
print("Shape:", a.shape)
print("Size:", a.size)
print("Datatype:", a.dtype)
print("Item Size:", a.itemsize)
print("Total Bytes:", a.nbytes)

Dimensions: 2
Shape: (2, 3)
Size: 6
Datatype: int64
Item Size: 8
Total Bytes: 48


In [ ]:
#3.Array Attributes

arr = np.array([[1,2,3],
               [4,5,6]])

print("dimensions",arr.ndim)
print("shape",arr.shape)
print("size",arr.size)
print("dtype",arr.dtype)

dimensions 2
shape (2, 3)
size 6
dtype int64


**4. Special Arrays
Learn:
zeros()
ones()
arange()
linspace()
eye()
random()**

1.   Summary Table
2. Function	Purpose
3. zeros()	Fill with 0
4. ones()	Fill with 1
5. eye()	Identity matrix
6. arange()	Sequence values
7. linspace()	Equal spacing
8. random.rand()	Random float
9. randint()	Random integers
10. full()	Same value fill





In [ ]:
a = np.zeros((2,3),dtype="int64")
print(a,a.shape)

b = np.ones((5,))
print(b,b.shape)

c = np.full((3,4),100)
print(c,c.shape)

d = np.eye(2,2)
print(d,d.shape)

c = np.arange(0,11,2)
print(c)

e = np.linspace(0,11,2)
print(e)

f = np.random.rand(3)
print(f)

g = np.full((2,2),3)
print(g)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0.]
 [0. 1.]] (2, 2)
[ 0  2  4  6  8 10]
[ 0. 11.]
[0.21384917 0.49767461 0.35463914]
[[3 3]
 [3 3]]


In [ ]:
#Practice Questions

#3×3 zeros matrix
arr1 = np.zeros((3,3))
print(arr1,arr1.shape)

print("   ")

#2×4 ones matrix
arr2 = np.ones((2,4))
print(arr2,arr2.shape)

print("   ")

#Create identity matrix of size 4.
arr3 = np.eye(4)
print(arr3)

#Create numbers from 1–20 using arange().
arr4 = np.arange(1,21)
print(arr4)

#Create 10 evenly spaced values between 0–100.
arr5 = np.linspace(0,100,10)
print(arr5)

#Generate 5 random integers between 1–50.
arr6 = np.random.randint(1,50,5)
print(arr6)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (3, 3)
   
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] (2, 4)
   
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
[ 1 40 45 17 27]


#### **5. Indexing & Slicing**

MOST IMPORTANT topic.
Learn:


- Positive indexing
- Negative indexing
- Row/column selection

In [ ]:
a = np.array([10,20,30,40,50,60])
print(a[0])
print(a[1:4])
print(a[-1])
print(a[-4])
print(a[:4])
print(a[-2:])
print(a[::2])
print()

10
[20 30 40]
60
30
[10 20 30 40]
[50 60]
[10 30 50]



**1. Positive Indexing**

In [ ]:
a = np.array([10,20,30,40,50])

print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])

10
20
30
40
50


**2. Negative Indexing**

In [ ]:
print(a[-1])
print(a[-2])
print(a[-3])
print(a[-4])
print(a[-5])

50
40
30
20
10


**3. Row Selection in 2D Arrays**

In [ ]:
b = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
print(b[0])

[1 2 3]


In [ ]:
print(b[1])

[4 5 6]


In [ ]:
print(b[2])

[7 8 9]


##### MOST IMPORTANT Interview
---
##### Concepts   Code	Meaning
---
1. a[0]	First element
2. a[-1]	Last element
3. b[1]	Second row
4. b[:,1]	Second column
5. b[1,2]	Specific element

In [ ]:
#array[row,column]

print(b[:,0])

[1 4 7]


In [ ]:
print(b[:,1])

[2 5 8]


In [ ]:
print(b[:,2])

[3 6 9]


In [ ]:
print(b[1,2])

6


**Operations on Arrays**

In [ ]:
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])

print(n1+n2)#1.Addition Operation
print(n1-n2)#2.Subtraction Operation
print(n1*n2)#3.Multiplication Operation
print(n1/n2)#4.Division Operation
print(n1**2)#5.Power Operation
print(n1%2)#6.Modulus Operation
print(n1+10)#7.Scalar Operations
print(n1 * 5)#8.Multiply Scalar
print(n1>n2) #9.Comparison Operations
print(n1[n1>1])#10.Boolean Masking

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[1 0 1]
[11 12 13]
[ 5 10 15]
[False False False]
[2 3]


Aggregation Operations

In [ ]:
print(n1.sum())

6


In [ ]:
print(n1.mean())

2.0


In [ ]:
print(n1.max())

3


In [ ]:
print(n1.min())

1


In [ ]:
marks = np.array([78,88,98,67,99,62,66,70])

print("Average:",marks.mean())
print("Highest",marks.max())
print("lowest",marks.min())
print("Passed",marks[marks>=70])

Average: 78.5
Highest 99
lowest 62
Passed [78 88 98 99 70]


In [ ]:
#Practice Questions

a=np.array([10,20,30])
b=np.array([1,2,3])


print("addition",a+b)
print("subtraction",a-b)
print("Multiplication",a*b)
print("Division",a/b)

#Add 50 to every element.
print(a+50)
print(b+50)

#Multiply all elements by 3.
print(a*3)

# Print elements greater than 15.
print(a[a>15])

#Find:
# Sum
print(a.sum())
# Mean
mean = np.mean(a)
#std
std_dev = np.std(a)

normalized_arr = (a-mean)/std_dev
# Max
print(a.max())
# Min
print(a.min())

addition [11 22 33]
subtraction [ 9 18 27]
Multiplication [10 40 90]
Division [10. 10. 10.]
[60 70 80]
[51 52 53]
[30 60 90]
[20 30]
60
30
10


In [ ]:
num1 = np.array([1,2,3,4])
num2 = np.array([1,2,3,4])

print(num1+num2)
print(num1-num2)
print(50+num1)
print(num1[num1<3])

m = np.mean(num1)
print(m)

n = np.std(num1)
print(n)

n1 = (num1-m)/n
print(n1)

[2 4 6 8]
[0 0 0 0]
[51 52 53 54]
[1 2]
2.5
1.118033988749895
[-1.34164079 -0.4472136   0.4472136   1.34164079]


**BroadCasting**

In [ ]:
arr = np.array([1,2,3,4])
arr2 = np.array([[1,2,3,4], [1,2,3,4]])

print(arr.shape)
print(arr2.shape)
print(arr + arr2)

(4,)
(2, 4)
[[2 4 6 8]
 [2 4 6 8]]


In [ ]:
#Scalar Broadcasting

a = np.array([1,2,3])

print(a+10)

[11 12 13]


In [ ]:
#Scalar Multiplication

a = np.array([1,2,3,4])

print(a*2)


[2 4 6 8]


In [ ]:
#Broadcasting with Two Arrays
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print(a1+a2)


[5 7 9]


In [ ]:
#2d broadcasting

a = np.array([[1,2,3],
              [4,5,6]
              ])

b = np.array([10,20,30])

c = a+b
print(c)

print(c.shape)

[[11 22 33]
 [14 25 36]]
(2, 3)


In [ ]:
#Broadcasting Error

a = np.array([1,2,3])
a2 = np.array([1,2,8])

print(a+a2)

[ 2  4 11]


In [ ]:
#Advanced Broadcasting — Column Vector
a = np.array([[1],
              [2],
              [3]
              ])

b = np.array([10,20,30])
print(a+b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
#Broadcasting with Different Dimensions
a = np.array([[1,2,3]])

b = np.array([[10],
             [20],
             [30]])
print(a+b)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
#Example:-

sales = np.array([100,200,300])

tax = 0.18

final_price = sales+(sales*tax)

print(final_price)

[118. 236. 354.]


### **MOST IMPORTANT Interview Question**

**Why is broadcasting important?**

**Answer:**

Broadcasting allows NumPy to perform
fast vectorized operations without loops,
making computations memory efficient
and high performance.

In [ ]:
# Practice Questions
# Beginner
# Add 50 to array
a = np.array([1,2,3])
print(a+50)

# Multiply array by 10
print(a*10)


[51 52 53]
[10 20 30]


In [ ]:
#practice question
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([10,20,30])

print(a+b)

[[11 22 33]
 [14 25 36]]


In [ ]:
#1. Scalar Broadcasting
a = np.array([5,10,15])
print(a+100)

#2. Array + Array

a1 = np.array([1,2,3])
b1 = np.array([10,20,30])
print(a1+b1)

#2D + 1D Broadcasting

c = np.array([[1,2,3],[4,5,6]])
d = np.array([10,20,30])
print(c+d)

#4. Column Broadcasting
a2 = np.array([[1],
              [2],
              [3]])

b2 = np.array([10,20,30])
c1 = a2+b2
print(c1)

#shape checking
print(a2.shape)
print(b2.shape)

[105 110 115]
[11 22 33]
[[11 22 33]
 [14 25 36]]
[[11 21 31]
 [12 22 32]
 [13 23 33]]
(3, 3)


In [ ]:
#copy vs view

# arr = [1,2,3,4]
# sub_arr = arr[1:3]
# print(sub_arr)
# sub_arr[0] = 200
# print(sub_arr)
# print(arr)


arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)


[2 3]
[200   3]
[  1 200   3   4   5]


**Random**

In [ ]:
a = np.random.rand(5)
print(a)

[0.85320285 0.11409682 0.29793667 0.13895087 0.77442091]


In [ ]:
a = np.random.rand(2,3)
print(a)

[[0.89581019 0.90432188 0.36325948]
 [0.05121367 0.49218891 0.78672141]]


In [ ]:
a = np.random.randint(1,10,5)
print(a)

[5 2 3 2 7]


In [ ]:
a = np.random.randn(5)
print(a)

[-0.16265665 -1.75572206  0.51019523  0.20191881 -0.03969694]


In [ ]:
np.random.seed(1)

print(np.random.randint(1,10,5))

[6 9 6 1 1]


In [ ]:
a = np.random.choice([1,2,3,4],5)
print(a)

[2 1 4 2 1]


In [ ]:
a = np.random.randn(5)
print(a)

[ 0.74533866 -1.02453436  0.05120077  0.62033456  1.58832773]


In [ ]:
a = np.random.randint(1,10,6)
print(a)

[9 3 7 3 6 7]


In [ ]:
np.random.seed(1)
print(np.random.randint(1,20,5))

[ 6 12 13  9 10]


In [ ]:
a = np.random.choice([10,20,30,40],5)
print(a)

[40 20 40 10 10]


In [ ]:
a = np.array([1,2,3,4,5])
np.random.shuffle(a)
print(a)

[3 4 2 5 1]


In [ ]:
a = np.random.uniform(1,100,5)
print(a)

[39.40316338 67.30485764 93.61836801 84.78478075 32.01407818]


In [ ]:
print(np.random.rand(3))
print(np.random.randint(1,10,5))
print(np.random.randn(5))
print(np.random.choice([1,2,3],3))

[0.53589641 0.66379465 0.51488911]
[6 8 9 5 5]
[-0.74795374  2.0867325   0.52647831  0.983809   -1.92220001]
[1 2 3]


### **Difference Between rand() and randint()**


rand() Float values

randint()	Integer values

In [ ]:
#Practice Questions

a = np.random.rand(5)
print(a)

a1 = np.random.randint(1,50,10)
print('a1 =',a1)


a2 = np.random.rand(2,3)
print(a2)

np.random.seed(1)
print(np.random.randint(1,20,5))

a3 = np.array([1,2,3,4])
np.random.shuffle(a3)
print(a3)



[0.23608898 0.39658073 0.38791074 0.66974604 0.93553907]
a1 = [21 38 19 21 12 43 29 30 15  5]
[[0.4173048  0.55868983 0.14038694]
 [0.19810149 0.80074457 0.96826158]]
[ 6 12 13  9 10]
[1 3 2 4]


In [ ]:
colors = ["red","green","orange"]
print(np.random.choice(colors,4))

['green' 'red' 'orange' 'green']


### **Reshaping Array Numpy**

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6])
print(a.reshape(2,3))
print(a.reshape(-1,2))
print("----")
print(a.reshape(3,2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
----
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.reshape(2,2,2))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
a = np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]]])
print(a.ndim)

print(a.flatten())


3
[1 2 3 4 5 6 7 8 9]


In [ ]:
a = np.array([
 [1,2,3],
 [4,5,6]
])

print(a.T)

[[1 4]
 [2 5]
 [3 6]]


###**NumPy Aggregation Functions**

### **Aggregation means:**

Combining multiple values
into a single summary value.

In [ ]:
#sum()
a = np.array([10,20,30,40,50])
print(a.sum())
# mean()
print('mean =',a.mean())
#max()
print('max =',a.max())
#min()
print('min = ',a.min())
#std()
print("std = ",a.std())
#var()
print("Var = ",a.var())
#median()
print("median = ",np.median(a))
#argmax()
print('argmax = ',a.argmax())
#argmin()
print('argmin = ',a.argmin())

150
mean = 30.0
max = 50
min =  10
std =  14.142135623730951
Var =  200.0
median =  30.0
argmax =  4
argmin =  0


In [ ]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
print(a.sum())
print(a.sum(axis=0)) #Column operation
print(a.sum(axis=1)) #Row operation



21
[5 7 9]
[ 6 15]


In [ ]:
#Practice Question

sales = np.array([1000,1200,1500,1700,1300])

print("Total Sales:",sales.sum())
print("Average Sales:", sales.mean())
print("Highest Sale:", sales.max())
print("Lowest Sale:", sales.min())

Total Sales: 6700
Average Sales: 1340.0
Highest Sale: 1700
Lowest Sale: 1000


In [ ]:
a = np.array([
    [10,20,30],
    [40,50,60]
])

print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

210
[50 70 90]
[ 60 150]


In [ ]:
marks = np.array([78,85,92,66,88])

print("avg",marks.mean())
print("highest",marks.max())
print('lowest',marks.min())
print('index of highest marks = ',marks.argmax())

avg 81.8
highest 92
lowest 66
index of highest marks =  2


### **Boolean Masking & Filtering**


In [ ]:
a = np.array([10,20,30,40,50])
print(a>25)

[False False  True  True  True]


In [ ]:
a = np.array([10,20,30,40,50])

# Greater than
print("Greater than 25:")
print(a[a > 25])

# Less than
print("\nLess than 25:")
print(a[a < 25])

# Equal to
print("\nEqual to 30:")
print(a[a == 30])

# Not equal to
print("\nNot equal to 30:")
print(a[a != 30])

# Greater than or equal to
print("\nGreater than or equal to 30:")
print(a[a >= 30])

# Less than or equal to
print("\nLess than or equal to 30:")
print(a[a <= 30])

# AND condition
print("\nGreater than 20 AND less than 50:")
print(a[(a > 20) & (a < 50)])

# OR condition
print("\nLess than 20 OR greater than 40:")
print(a[(a < 20) | (a > 40)])

Greater than 25:
[30 40 50]

Less than 25:
[10 20]

Equal to 30:
[30]

Not equal to 30:
[10 20 40 50]

Greater than or equal to 30:
[30 40 50]

Less than or equal to 30:
[10 20 30]

Greater than 20 AND less than 50:
[30 40]

Less than 20 OR greater than 40:
[10 50]


In [ ]:
marks = np.array([78,85,92,66,88])

print("Passed with distinction:")
print(marks[marks >= 80])

print("Need improvement:")
print(marks[marks < 80])

print("Top performers (80-90):")
print(marks[(marks >= 80) & (marks <= 90)])

Passed with distinction:
[85 92 88]
Need improvement:
[78 66]
Top performers (80-90):
[85 88]


In [ ]:
marks = np.array([78, 85, 92, 66, 88])

top_students = marks[marks > 80]

print("Top Students Marks:", top_students)

Top Students Marks: [85 92 88]


## **Linear Algebra**

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

[[ 6  8]
 [10 12]]


In [ ]:
#Matrix Addition
print(" Addition = \n",A+B)

#Matrix Subtraction
print("Subtraction = \n",A-B)

#Matrix Multiplication
print("Multiplication = \n",A*B)

#Transpose
print("A transpose = \n",A.T)
print("B transpose = \n",B.T)

# Determinant
print("Determinant = ",np.linalg.det(A))

#Inverse
print("Inverse = \n",np.linalg.inv(A))

#Eigenvalues and Eigenvectors
values, vectors = np.linalg.eig(A)

print("Eigenvalues:", values)
print("Eigenvectors:",vectors)

#Rank of Matrix
print("Rank = ",np.linalg.matrix_rank(A))


 Addition = 
 [[ 6  8]
 [10 12]]
Subtraction = 
 [[-4 -4]
 [-4 -4]]
Multiplication = 
 [[ 5 12]
 [21 32]]
A transpose = 
 [[1 3]
 [2 4]]
B transpose = 
 [[5 7]
 [6 8]]
Determinant =  -2.0000000000000004
Inverse = 
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Rank =  2


In [ ]:
# Linear Equation

A = np.array([[2,1],
             [1,3]])

B = np.array([5,6])

x = np.linalg.solve(A,B)
print(x)

[1.8 1.4]


**LINEAR ALGEBRA**

Most Important numpy.linalg Functions
Function	Purpose

np.linalg.det() Determinant

np.linalg.inv()	Inverse

np.linalg.eig()	Eigenvalues & Eigenvectors

np.linalg.solve()	Solve linear equations

np.linalg.matrix_rank()	Matrix rank

np.linalg.norm()	Vector/Matrix norm

np.linalg.svd()	Singular Value Decomposition



In [ ]:
a = np.array([[4,2],
              [1,3]])

print("Matrix",a)

print("Determine",np.linalg.det(a))

print("Inverse",np.linalg.inv(a))

print("Transpose",a.T)

Matrix [[4 2]
 [1 3]]
Determine 10.000000000000002
Inverse [[ 0.3 -0.2]
 [-0.1  0.4]]
Transpose [[4 1]
 [2 3]]


In [ ]:
#practice Question
A = np.array([[2, 4],
              [1, 3]])

B = np.array([[5, 6],
              [7, 8]])

print("Addition:",A+B)

print("Subtraction:",A-B)

print("Multiplication:",A*B)

print("Transpose:",A.T)
print("Transpose:",B.T)


print("Inverse of A:",np.linalg.inv(A))

print("Rank of A:",np.linalg.matrix_rank(A))

Addition: [[ 7 10]
 [ 8 11]]
Subtraction: [[-3 -2]
 [-6 -5]]
Multiplication: [[10 24]
 [ 7 24]]
Transpose: [[2 1]
 [4 3]]
Transpose: [[5 7]
 [6 8]]
Inverse of A: [[ 1.5 -2. ]
 [-0.5  1. ]]
Rank of A: 2
